---
- name: install packages
  action: apt pkg={{item}} state=installed
  with_items:
  - haproxy

- name: create pemfile
  command: bash -c "cat /etc/apache2/ssl/server.crt /etc/apache2/ssl/server.key > /etc/apache2/ssl/cert_plus_key.pem"
  args:
    creates: "/etc/apache2/ssl/cert_plus_key.pem"
  notify: "restart haproxy"

- name: haproxy config
  template:
    src: osrf-ws-http-proxy.j2
    dest: "/etc/haproxy/haproxy.cfg"
  notify: "restart haproxy"

- name: start haproxy
  service:
    name: haproxy
    state: started