- include_tasks: apache-debian.yml
# fixme

- name: a2ensite eg
  command: a2ensite eg
  notify:
  - restart apache2

- name: a2dissite 000-default
  command: a2dissite 000-default
  notify:
  - restart apache2