
- name: evergreen js repo ownership
  file:
    path: "{{ evergreen_src_dir }}/Open-ILS/src/eg2/"
    owner: opensrf
    group: opensrf
    mode: 0755

- name: npm install
  command: npm install
  args:
    chdir: "{{ evergreen_src_dir }}/Open-ILS/src/eg2/"
  become: true
  become_user: opensrf

- name: npm install -g ng
  command: npm install -g @angular/cli
  args:
    chdir: "{{ evergreen_src_dir }}/Open-ILS/src/eg2/"
  become: true

- name: ng build
  command: ng build
  args:
    chdir: "{{ evergreen_src_dir }}/Open-ILS/src/eg2/"
