- name: hosts file
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"    

# Things i find useful in my VM
- name: install dev tools
  action: apt pkg={{item}} state=installed
  with_items:
  - vim
  - ack